version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: ruby:3.2
    command: bash -c "bundle install && rails db:create && rails db:migrate && rails server -b '0.0.0.0'"
    volumes:
      - ".:/task_managment"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/task_managment

volumes:
  postgres_data:
